spring:
  datasource:
    url: jdbc:postgresql://db:5432/mentor
    username: mentor
    password: mentor
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
